const DUMMY_RESULTS = [
  {
    imdbID: "tt0800039",
    tmdbID: "9870",
    imdbRating: 71,
    imdbVoteCount: 286248,
    tmdbRating: 64,
    backdropPath: "/s39aQY3dK1s6ARrUKP5yeq824nR.jpg",
    backdropURLs: {
      300: "https://image.tmdb.org/t/p/w300/s39aQY3dK1s6ARrUKP5yeq824nR.jpg",
      780: "https://image.tmdb.org/t/p/w780/s39aQY3dK1s6ARrUKP5yeq824nR.jpg",
      1280: "https://image.tmdb.org/t/p/w1280/s39aQY3dK1s6ARrUKP5yeq824nR.jpg",
      original:
        "https://image.tmdb.org/t/p/original/s39aQY3dK1s6ARrUKP5yeq824nR.jpg",
    },
    originalTitle: "Forgetting Sarah Marshall",
    genres: [35, 18, 10749],
    countries: ["US"],
    year: 2008,
    runtime: 111,
    cast: [
      "Jason Segel",
      "Kristen Bell",
      "Mila Kunis",
      "Russell Brand",
      "Bill Hader",
      "Jonah Hill",
      "Liz Cackowski",
    ],
    significants: ["Nicholas Stoller"],
    title: "Forgetting Sarah Marshall",
    overview:
      "When Sarah Marshall dumps aspiring musician Peter Bretter for rock star Aldous Snow, Peter's world comes crashing down. His best friend suggests that Peter should get away from everything and to fly off to Hawaii to escape all his problems. After arriving in Hawaii and meeting the beautiful Rachel Jansen, Peter is shocked to see not only Aldous Snow in Hawaii, but also Sarah Marshall.",
    tagline: "You lose some, you get some.",
    video: "K4xD8ZMdJms",
    posterPath: "/6VKSQ40z76zi6nMqX7zjCZKfsBa.jpg",
    posterURLs: {
      92: "https://image.tmdb.org/t/p/w92/6VKSQ40z76zi6nMqX7zjCZKfsBa.jpg",
      154: "https://image.tmdb.org/t/p/w154/6VKSQ40z76zi6nMqX7zjCZKfsBa.jpg",
      185: "https://image.tmdb.org/t/p/w185/6VKSQ40z76zi6nMqX7zjCZKfsBa.jpg",
      342: "https://image.tmdb.org/t/p/w342/6VKSQ40z76zi6nMqX7zjCZKfsBa.jpg",
      500: "https://image.tmdb.org/t/p/w500/6VKSQ40z76zi6nMqX7zjCZKfsBa.jpg",
      780: "https://image.tmdb.org/t/p/w780/6VKSQ40z76zi6nMqX7zjCZKfsBa.jpg",
      original:
        "https://image.tmdb.org/t/p/original/6VKSQ40z76zi6nMqX7zjCZKfsBa.jpg",
    },
    age: -1,
    streamingInfo: {
      crave: {
        ca: {
          link: "https://www.crave.ca/en/movies/forgetting-sarah-marshall",
          added: 1627818869,
          leaving: 0,
        },
      },
      prime: {
        ca: {
          link: "https://www.primevideo.com/detail/0NLOM68HB66N8X344BGLAB7432/",
          added: 1608537242,
          leaving: 0,
        },
      },
    },
    originalLanguage: "en",
  },
  {
    imdbID: "tt0120915",
    tmdbID: "1893",
    imdbRating: 65,
    imdbVoteCount: 803491,
    tmdbRating: 65,
    backdropPath: "/5fu7fzy4NZTsL1Jap00UBIInAuB.jpg",
    backdropURLs: {
      300: "https://image.tmdb.org/t/p/w300/5fu7fzy4NZTsL1Jap00UBIInAuB.jpg",
      780: "https://image.tmdb.org/t/p/w780/5fu7fzy4NZTsL1Jap00UBIInAuB.jpg",
      1280: "https://image.tmdb.org/t/p/w1280/5fu7fzy4NZTsL1Jap00UBIInAuB.jpg",
      original:
        "https://image.tmdb.org/t/p/original/5fu7fzy4NZTsL1Jap00UBIInAuB.jpg",
    },
    originalTitle: "Star Wars: Episode I - The Phantom Menace",
    genres: [28, 12, 14],
    countries: ["US"],
    year: 1999,
    runtime: 136,
    cast: [
      "Liam Neeson",
      "Ewan McGregor",
      "Natalie Portman",
      "Jake Lloyd",
      "Ian McDiarmid",
      "Pernilla August",
      "Oliver Ford Davies",
    ],
    significants: ["George Lucas"],
    title: "Star Wars: Episode I - The Phantom Menace",
    overview:
      "Anakin Skywalker, a young slave strong with the Force, is discovered on Tatooine. Meanwhile, the evil Sith have returned, enacting their plot for revenge against the Jedi.",
    tagline:
      "Every generation has a legend. Every journey has a first step. Every saga has a beginning.",
    video: "bD7bpG-zDJQ",
    posterPath: "/6wkfovpn7Eq8dYNKaG5PY3q2oq6.jpg",
    posterURLs: {
      92: "https://image.tmdb.org/t/p/w92/6wkfovpn7Eq8dYNKaG5PY3q2oq6.jpg",
      154: "https://image.tmdb.org/t/p/w154/6wkfovpn7Eq8dYNKaG5PY3q2oq6.jpg",
      185: "https://image.tmdb.org/t/p/w185/6wkfovpn7Eq8dYNKaG5PY3q2oq6.jpg",
      342: "https://image.tmdb.org/t/p/w342/6wkfovpn7Eq8dYNKaG5PY3q2oq6.jpg",
      500: "https://image.tmdb.org/t/p/w500/6wkfovpn7Eq8dYNKaG5PY3q2oq6.jpg",
      780: "https://image.tmdb.org/t/p/w780/6wkfovpn7Eq8dYNKaG5PY3q2oq6.jpg",
      original:
        "https://image.tmdb.org/t/p/original/6wkfovpn7Eq8dYNKaG5PY3q2oq6.jpg",
    },
    age: 6,
    streamingInfo: {
      disney: {
        ca: {
          link: "https://www.disneyplus.com/movies/-/2ezYynkgW1AH",
          added: 1606703120,
          leaving: 0,
        },
      },
    },
    originalLanguage: "en",
  },
  {
    imdbID: "tt5294550",
    tmdbID: "446791",
    imdbRating: 68,
    imdbVoteCount: 85737,
    tmdbRating: 65,
    backdropPath: "/wJLTRnFKAVDDD7ci2L1eVnNJ7aI.jpg",
    backdropURLs: {
      300: "https://image.tmdb.org/t/p/w300/wJLTRnFKAVDDD7ci2L1eVnNJ7aI.jpg",
      780: "https://image.tmdb.org/t/p/w780/wJLTRnFKAVDDD7ci2L1eVnNJ7aI.jpg",
      1280: "https://image.tmdb.org/t/p/w1280/wJLTRnFKAVDDD7ci2L1eVnNJ7aI.jpg",
      original:
        "https://image.tmdb.org/t/p/original/wJLTRnFKAVDDD7ci2L1eVnNJ7aI.jpg",
    },
    originalTitle: "All the Money in the World",
    genres: [1, 80, 18],
    countries: ["US", "IT", "GB"],
    year: 2017,
    runtime: 132,
    cast: [
      "Michelle Williams",
      "Christopher Plummer",
      "Mark Wahlberg",
      "Romain Duris",
      "Timothy Hutton",
      "Charlie Plummer",
      "Charlie Shotwell",
    ],
    significants: ["Ridley Scott"],
    title: "All the Money in the World",
    overview:
      "The story of the kidnapping of 16-year-old John Paul Getty III and the desperate attempt by his devoted mother to convince his billionaire grandfather Jean Paul Getty to pay the ransom.",
    tagline: "J. Paul Getty had a fortune. Everyone else paid the price.",
    video: "muk33nlCnQk",
    posterPath: "/q6nE9Hf0ezszjI4DbCxwzQ73MMy.jpg",
    posterURLs: {
      92: "https://image.tmdb.org/t/p/w92/q6nE9Hf0ezszjI4DbCxwzQ73MMy.jpg",
      154: "https://image.tmdb.org/t/p/w154/q6nE9Hf0ezszjI4DbCxwzQ73MMy.jpg",
      185: "https://image.tmdb.org/t/p/w185/q6nE9Hf0ezszjI4DbCxwzQ73MMy.jpg",
      342: "https://image.tmdb.org/t/p/w342/q6nE9Hf0ezszjI4DbCxwzQ73MMy.jpg",
      500: "https://image.tmdb.org/t/p/w500/q6nE9Hf0ezszjI4DbCxwzQ73MMy.jpg",
      780: "https://image.tmdb.org/t/p/w780/q6nE9Hf0ezszjI4DbCxwzQ73MMy.jpg",
      original:
        "https://image.tmdb.org/t/p/original/q6nE9Hf0ezszjI4DbCxwzQ73MMy.jpg",
    },
    age: -1,
    streamingInfo: {
      netflix: {
        ca: {
          link: "https://www.netflix.com/title/80201987/",
          added: 1657793585,
          leaving: 0,
        },
      },
    },
    originalLanguage: "en",
  },
  {
    imdbID: "tt0404163",
    tmdbID: "19126",
    imdbRating: 58,
    imdbVoteCount: 4599,
    tmdbRating: 55,
    backdropPath: "/5IokXOZYTeUhoNyZ2YIg01qrO6P.jpg",
    backdropURLs: {
      300: "https://image.tmdb.org/t/p/w300/5IokXOZYTeUhoNyZ2YIg01qrO6P.jpg",
      780: "https://image.tmdb.org/t/p/w780/5IokXOZYTeUhoNyZ2YIg01qrO6P.jpg",
      1280: "https://image.tmdb.org/t/p/w1280/5IokXOZYTeUhoNyZ2YIg01qrO6P.jpg",
      original:
        "https://image.tmdb.org/t/p/original/5IokXOZYTeUhoNyZ2YIg01qrO6P.jpg",
    },
    originalTitle: "Even Money",
    genres: [80, 18],
    countries: ["DE", "US"],
    year: 2006,
    runtime: 113,
    cast: [
      "Kim Basinger",
      "Kelsey Grammer",
      "Forest Whitaker",
      "Nick Cannon",
      "Ray Liotta",
      "Jay Mohr",
      "Danny DeVito",
    ],
    significants: ["Mark Rydell"],
    title: "Even Money",
    overview:
      "Gambling addiction bring the stories of three otherwise unconnected people together as it destroys each of their lives.",
    tagline: "The Fix. The Gamble. The Betrayal. The Threat.",
    video: "_uoEhTD-ZZM",
    posterPath: "/63SdrM8TZbAi4R1Ju7yiIqBmpY3.jpg",
    posterURLs: {
      92: "https://image.tmdb.org/t/p/w92/63SdrM8TZbAi4R1Ju7yiIqBmpY3.jpg",
      154: "https://image.tmdb.org/t/p/w154/63SdrM8TZbAi4R1Ju7yiIqBmpY3.jpg",
      185: "https://image.tmdb.org/t/p/w185/63SdrM8TZbAi4R1Ju7yiIqBmpY3.jpg",
      342: "https://image.tmdb.org/t/p/w342/63SdrM8TZbAi4R1Ju7yiIqBmpY3.jpg",
      500: "https://image.tmdb.org/t/p/w500/63SdrM8TZbAi4R1Ju7yiIqBmpY3.jpg",
      780: "https://image.tmdb.org/t/p/w780/63SdrM8TZbAi4R1Ju7yiIqBmpY3.jpg",
      original:
        "https://image.tmdb.org/t/p/original/63SdrM8TZbAi4R1Ju7yiIqBmpY3.jpg",
    },
    age: 16,
    streamingInfo: {
      prime: {
        ca: {
          link: "https://www.primevideo.com/detail/0I5NQR99DM19B2XJPWDOELN1FB/",
          added: 1608511818,
          leaving: 0,
        },
      },
    },
    originalLanguage: "en",
  },
  {
    imdbID: "tt14376344",
    tmdbID: "814340",
    imdbRating: 73,
    imdbVoteCount: 17522,
    tmdbRating: 71,
    backdropPath: "/1LMGpNSUekWg3XCPweN33knQPW9.jpg",
    backdropURLs: {
      300: "https://image.tmdb.org/t/p/w300/1LMGpNSUekWg3XCPweN33knQPW9.jpg",
      780: "https://image.tmdb.org/t/p/w780/1LMGpNSUekWg3XCPweN33knQPW9.jpg",
      1280: "https://image.tmdb.org/t/p/w1280/1LMGpNSUekWg3XCPweN33knQPW9.jpg",
      original:
        "https://image.tmdb.org/t/p/original/1LMGpNSUekWg3XCPweN33knQPW9.jpg",
    },
    originalTitle: "Cha Cha Real Smooth",
    genres: [35, 18],
    countries: ["US"],
    year: 2022,
    runtime: 108,
    cast: [
      "Cooper Raiff",
      "Dakota Johnson",
      "Vanessa Burghardt",
      "Evan Assante",
      "Leslie Mann",
      "Brad Garrett",
      "Raúl Castillo",
    ],
    significants: ["Cooper Raiff"],
    title: "Cha Cha Real Smooth",
    overview:
      "Fresh out of college and stuck at his New Jersey home without a clear path forward, 22-year-old Andrew begins working as a party starter for bar/bat mitzvahs—where he strikes up a unique friendship with a young mom and her teenage daughter.",
    tagline: "Falling in love is easy. Growing up is hard.",
    video: "QRyyagJ9GPo",
    posterPath: "/iUvoVhvwTlP8DofoqeIu7QAGLAe.jpg",
    posterURLs: {
      92: "https://image.tmdb.org/t/p/w92/iUvoVhvwTlP8DofoqeIu7QAGLAe.jpg",
      154: "https://image.tmdb.org/t/p/w154/iUvoVhvwTlP8DofoqeIu7QAGLAe.jpg",
      185: "https://image.tmdb.org/t/p/w185/iUvoVhvwTlP8DofoqeIu7QAGLAe.jpg",
      342: "https://image.tmdb.org/t/p/w342/iUvoVhvwTlP8DofoqeIu7QAGLAe.jpg",
      500: "https://image.tmdb.org/t/p/w500/iUvoVhvwTlP8DofoqeIu7QAGLAe.jpg",
      780: "https://image.tmdb.org/t/p/w780/iUvoVhvwTlP8DofoqeIu7QAGLAe.jpg",
      original:
        "https://image.tmdb.org/t/p/original/iUvoVhvwTlP8DofoqeIu7QAGLAe.jpg",
    },
    age: 16,
    streamingInfo: {
      apple: {
        ca: {
          link: "https://tv.apple.com/ca/movie/-/umc.cmc.6loo9fah7vwj2zpp7ehactlpd",
          added: 1666316186,
          leaving: 0,
        },
      },
    },
    originalLanguage: "en",
  },
];

export default DUMMY_RESULTS;
